Catalog list
agolokoz/iOS-FakeNFT-StarterProject-Public pull request #4
Opened 2023-12-13 14:23 UTC by agolokoz

https://github.com/users/agolokoz/projects/1/views/1?pane=issue&itemId=47455577

2023-12-14 17:46 UTC, protos17 requested changes

2023-12-14 17:46 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +                imageUrl: URL(string: collection.cover),
Здесь необходимо заменить на:

      imageUrl: URL(string: collection.cover.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? "")
      
 чтобы Kingfisher корректно работал с кириллицей

2023-12-14 17:46 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    lazy var viewModel: NftCatalogViewModel = {
1. ViewModel должна быть приватной и не видна снаружи вью-контроллера
2. Рекомендую для вью-модели написать протокол

2023-12-14 17:46 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    private var items = [NftCollectionBigCell.Item]()
Эти items должны находиться внутри вью-модели, здесь их не должно быть

2023-12-14 17:46 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +            sortButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -9)
Константы для констрейнтов рекомендую выносить в extension класса: 

       extension NftCatalogViewController {      
             private enum Constants {     
                        static let defaultOffset: CGFloat = 4    
                         ...           
             }       
       }

2023-12-14 17:46 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    private func didCollectionsChanged(_ collections: [NftCollection]?) {
Данный метод тоже должен быть внутри вью-модели, а во вью-контроллере мы должны создать привязку и лишь отображать необходимые данные, а за их подготовку отвечает вью-модель

2023-12-14 17:46 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    private func setLoading(_ isLoading: Bool) {
Данный метод должен вызываться через байндинг от вью-модели, которая должна сюда отправлять isLoading

2023-12-14 17:46 UTC, protos17 commented on FakeNFT/Scenes/Base/BaseViewController.swift
> +    var viewModel: VM { get }
Рекомендую убрать, потому что вью-модели должны быть приватными

2023-12-14 17:46 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogViewModel.swift
> +                return c1.nfts.count < c2.nfts.count
Рекомендую поставить сортировку от большего к меньшему

2023-12-15 08:46 UTC, agolokoz commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    lazy var viewModel: NftCatalogViewModel = {
Для чего нужен протокол?

2023-12-15 08:47 UTC, agolokoz commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    private var items = [NftCollectionBigCell.Item]()
Почему должны? Это ui-представление данных, а не часть бизнес-логики.

2023-12-15 08:48 UTC, agolokoz commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +            sortButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -9)
Для чего? Это значение используется в одном месте

2023-12-15 08:52 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    lazy var viewModel: NftCatalogViewModel = {
Протоколы нужны для полиморфизма, для тестирования, на реальной работе все будет покрыто протоколами, поэтому, при обучении это все нужно освоить

2023-12-15 08:54 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    private var items = [NftCollectionBigCell.Item]()
Все верно, но в MVVM view только отображает данные из viewModel и передает ему команды пользовательского взаимодействия

2023-12-15 08:55 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +            sortButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -9)
Это общая рекомендация ко всем константам констрейнтов, а не только к данному месту

2023-12-15 08:58 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    private var items = [NftCollectionBigCell.Item]()
https://practicum.yandex.ru/learn/ios-developer/courses/ed96807e-9cb7-4515-87a4-ab67f8ee5023/sprints/111752/topics/dad706a1-7f70-4dda-a6a1-1e617c56412e/lessons/e0e855b2-f248-47a3-aec1-3148aae0cf3f/

2023-12-15 09:12 UTC, agolokoz commented
@protos17 
> Необходимо в файл .md добавить информацию о выбранной командой архитектуре и способ верстки.

В задании сказано: 
"В вашем Pull Request приложена ссылка на таск трекер. В доске должна быть информация о вашем прогрессе:
...
декомпозиция эпика (приложенный текстовый документ .md)
...
"
В боковой панели таск-трекера есть эта информация. Путь до неё не очевиден, но что поделать, так инструмент.

> На странице с каталогами лучше было использовать UITableView, а не UICollectionView.

Чем лучше-то? Если придёт требование показывать по 2 коллекции в ряд, то нужно будет всё переписывать.

> Все данные для отображения должны храниться во вью-модели, у тебя данные хранятся во вью-контроллере;

Не согласен словом "должны". Всё зависит от подхода, выбранного в команде. Если во viewModel хранить данные, которые жёстко привязаны к ui, то при изменении ui-слоя придётся менять и viewModel слой, а такого, в идеале, быть не должно. 

> вью-модель должна быть приватной и не должна быть видна снаружи, потому что это вью-модель конкретного вью-контроллера;

С одной стороны да, с другой это будет мешать нормальной разработке. Я хочу, чтобы у меня была базовая сущность (абстрактный класс/протокол), который будет указывать на то, что здесь есть viewModel и я могу как-то с ней взаимодействовать. Например если я добавлю BaseViewModelViewController, в котором у меня будет код, который нужен на всех экранах, где есть viewModel. С приватным полем viewModel так сделать не получится, в Свифте нету protected полей и методов, остаётся только public. Да, я понимаю, что вьюмодель принадлежит только вьюконтроллеру и, в идеале, должна быть приватной. Но никто в здравом уме не будет обращаться к вью-модели вне вьюконтроллера, которому она принадлежит, а если и будет, то это кандидат на разъяснительную беседу или увольнение. В общем тут trade-off. 

> лучше всего инициализировать вью-модель при инициализации вью-контроллера

Почему "лучше всего"? Хотелось бы какие-нибудь аргументы, а не только предложения.

> При работе с гитом было бы круто задавать номера коммитам, как в таске

Что такое номера коммитов "как в таске"?

2023-12-15 09:55 UTC, agolokoz commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    lazy var viewModel: NftCatalogViewModel = {
> на реальной работе все будет покрыто протоколами
Вообще нет) Протоколы ради протоколов это плохо, будет только мешать разработке.
И далеко не во всех компаниях пишут юнит-тесты)

2023-12-15 09:55 UTC, protos17 commented
> @protos17
> 
> > Необходимо в файл .md добавить информацию о выбранной командой архитектуре и способ верстки.
> 
> В задании сказано: "В вашем Pull Request приложена ссылка на таск трекер. В доске должна быть информация о вашем прогрессе: ... декомпозиция эпика (приложенный текстовый документ .md) ... " В боковой панели таск-трекера есть эта информация. Путь до неё не очевиден, но что поделать, такой инструмент.
> 
____________________________________________________
 Да, можно эти данные тогда оставить там, но у меня нет доступа к этой доске, киньте тогда инвайт чтобы я зашел, потому что скорее всего она создана как приватная
____________________________________________________
> > На странице с каталогами лучше было использовать UITableView, а не UICollectionView.
> 
> А чем лучше? Если придёт требование показывать по 2 коллекции в ряд, то нужно будет всё переписывать. Вообще TableView это CollectionView для ленивых :D
> 
____________________________________________________
Здесь у нас есть готовый макет уже, второго ряда не предусмотрено. Просто рекомендую использовать принцип YAGNI и не добавлять то, что сейчас не нужно. Ну и дипломная работа у нас создана с таким учетом, чтобы этот экран был сверстан как TableView, а экран с самими NFT как CollectionView, потому что часто при поиске работы нужно показать что умеешь работать как с TableView, так и CollectionView. Это моя рекомендация, на работоспособность приложения никак не повлияет, просто так будет лучше)
____________________________________________________
>> 
> > Все данные для отображения должны храниться во вью-модели, у тебя данные хранятся во вью-контроллере;
> 
> Не согласен словом "должны". Всё зависит от подхода, выбранного в команде. Если во viewModel хранить данные, которые жёстко привязаны к ui, то при изменении ui-слоя придётся менять и viewModel слой, а такого, в идеале, быть не должно.
> 
____________________________________________________
Так в этом вся суть разделения, рекомендую еще раз почитать про MVVM, вью должна просто отображать то, что ей передает вью-модель через байндинги.
____________________________________________________
> > вью-модель должна быть приватной и не должна быть видна снаружи, потому что это вью-модель конкретного вью-контроллера;
> 
> С одной стороны да, с другой это будет мешать нормальной разработке. Я хочу, чтобы у меня была базовая сущность (абстрактный класс/протокол), который будет указывать на то, что здесь есть viewModel и я могу как-то с ней взаимодействовать. Например если я добавлю BaseViewModelViewController, в котором у меня будет код, который нужен на всех экранах, где есть viewModel. С приватным полем viewModel так сделать не получится, в Свифте нету protected полей и методов, остаётся только public. Да, я понимаю, что вьюмодель принадлежит только вьюконтроллеру и, в идеале, должна быть приватной. Но никто в здравом уме не будет обращаться к вью-модели вне вьюконтроллера, которому она принадлежит, а если и будет, то это кандидат на разъяснительную беседу или увольнение. В общем тут trade-off.
> 
____________________________________________________
Это не только про красоту кода, но и диспетчеризацию. Для такой реализации необходимо использовать механизм наследования:
1. Создать базовый протокол для вью-моделей
2. Для каждой конкретной вью-модели написать свой протокол и подписывать этот протокол под базовый
____________________________________________________
> > лучше всего инициализировать вью-модель при инициализации вью-контроллера
> 
> Почему "лучше всего"? Хотелось бы какие-нибудь аргументы, а не только предложения.
> 
____________________________________________________
Это принцип Single responsibility из SOLID, вью-контроллер не должен отвечать за создание вью-модели, поэтому и лучше создавать его в том же месте, где создается вью-контроллер. Плюс это пригодится при тестировании
____________________________________________________
> > При работе с гитом было бы круто задавать номера коммитам, как в таске
> 
> Что такое номера коммитов "как в таске"?
У каждой созданной таски есть свой номер, поэтому принято коммитам присваивать название конкретной таски, например, в джире:
CLCAB-1234-addded-sorting

2023-12-15 09:59 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    lazy var viewModel: NftCatalogViewModel = {
Тут мы обучаем лучшим практикам. Понятно, что можно не писать никаких протоколов, не писать тестов, да и вообще сущности не разделять и не использовать SOLID и т.д. Тут вопрос к качеству кода

2023-12-15 10:03 UTC, agolokoz commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    private var items = [NftCollectionBigCell.Item]()
По такой логике мы должны загружать байты картинки в массив байтов и из ViewModel передавать их во view слой, вместо url :D Но почему-то мы этого не делаем, а отдаём логику загрузки и кеширования на ui-слой, хотя, по-хорошему, этим должна заниматься viewModel и сервисы. Я это всё к тому, что нет смысла делать прям по архитектуре, которая периодчески не помогает, а только усложняет разработку. Пользователям вообще безразлично какой код в приложении, им главное, чтобы оно работало правильно и не тормозило. Я не за то, чтобы писать неразберимый спагетти-код, я за здравый смысл и НЕ за слепое следование тому, что написали какие-то там дяди, которые такие же, как и мы, разработчики но с чуть бОльшим опытом. Работать с этим кодом команде (в данном случае мне), мне удобнее и понятнее вот с таким подходом и этот подход ничего не нарушает.

2023-12-15 10:04 UTC, agolokoz commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +            sortButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -9)
В данном случае рекомендация не имеет профита. Она только увеличит количество строк кода и время на поиски значения, потому что когда разработчик увидит, что значение отступа лежит в константе, ему придётся переходить к этому месту и уже там исправлять а не на месте. Я был бы абсолютно согласен с комментарием, если бы константа использовалась в 2х и более местах. А сейчас вынос не имеет смысла.

2023-12-15 10:06 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    private var items = [NftCollectionBigCell.Item]()
Все верно, ui должна только отображать необходимые данные. Это у нас учебный проект и такие требования. На реальных задачах можно делать как вздумается

2023-12-15 10:08 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +            sortButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -9)
Да, это усложнит код, но при необходимости замены все константы будут в одном месте. Конкретно здесь, где только одна константа, нет особого профита, но если применять данный подход, то нужно использовать везде

2023-12-16 14:08 UTC, agolokoz commented on FakeNFT/Scenes/Catalog/NftCatalogController.swift
> +    lazy var viewModel: NftCatalogViewModel = {
<img width="915" alt="Screenshot 2023-12-16 at 18 07 41" src="https://github.com/agolokoz/iOS-FakeNFT-StarterProject-Public/assets/5617556/54c2c15d-f53e-4eaf-bc8b-adee3bf16f17">

2023-12-17 12:34 UTC, protos17 approved these changes

2023-12-17 12:34 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogViewModel.swift
> +final class NftCatalogViewModel: BaseViewModel {
propertyWrappers нельзя указывать в протоколе, поэтому, в таком случае, протокол с байндингами следует создавать примерно так:

     protocol INftCatalogViewModel: IBaseViewModel {
          var items: Observable<[NftCollectionBigCell.Item]> { get }
          var isLoading: Observable<Bool> { get }
          func didSortByNameSelected()
          func didSortByCountSelected()
          func didRefreshed()
      }

А в самом классе указывать:

     final class NftCatalogViewModel: BaseViewModel, INftCatalogViewModel {
          var items: Observable<[NftCollectionBigCell.Item]> {
              $_items
          }
    
          var isLoading: Observable<Bool> {
              $_isLoading
          }

          @Observable
          private var _items = [NftCollectionBigCell.Item]()
    
          @Observable
          private (set) var _isLoading = false
      }

2023-12-17 12:34 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogViewController.swift
> +    private var items = [NftCollectionBigCell.Item]()
В нем нет необходимости, все нужные данные хранятся во вью-моделе

2023-12-17 12:34 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogViewController.swift
> +        return items.count
Здесь просто стоит указать:

      viewModel.items.wrappedValue.count

2023-12-17 12:34 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogViewController.swift
> +        cell.bind(item: items[indexPath.row])
Здесь тоже стоит поменять на:

     cell.bind(item: viewModel.items.wrappedValue[indexPath.row])

2023-12-17 12:34 UTC, protos17 commented on FakeNFT/Scenes/Catalog/NftCatalogViewModel.swift
> +            case .failure(_):
Рекомендую в алерте еще и отображать текст ошибки:

      case .failure(let error):
           showErrorAlert(error.localizedDesciption) { ... }

2023-12-17 18:05 UTC, merged